package id.tiooooo.pokedata.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF3B82F6)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFDDEBFF)
val onPrimaryContainerLight = Color(0xFF102C57)

val secondaryLight = Color(0xFF10B981)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD2FADF)
val onSecondaryContainerLight = Color(0xFF085F3D)

val tertiaryLight = Color(0xFF6366F1)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFE0E7FF)
val onTertiaryContainerLight = Color(0xFF1E1B4B)

val errorLight = Color(0xFFEF4444)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFE4E0)
val onErrorContainerLight = Color(0xFF7A1C1C)

val backgroundLight = Color(0xFFF9FAFB)
val onBackgroundLight = Color(0xFF111827)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF111827)
val surfaceVariantLight = Color(0xFFE5E7EB)
val onSurfaceVariantLight = Color(0xFF374151)

val outlineLight = Color(0xFF9CA3AF)
val outlineVariantLight = Color(0xFFE5E7EB)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF1F2937)
val inverseOnSurfaceLight = Color(0xFFF3F4F6)
val inversePrimaryLight = Color(0xFF60A5FA)
val surfaceDimLight = Color(0xFFE5E7EB)
val surfaceBrightLight = Color(0xFFFFFFFF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF1F5F9)
val surfaceContainerLight = Color(0xFFE2E8F0)
val surfaceContainerHighLight = Color(0xFFD1D5DB)
val surfaceContainerHighestLight = Color(0xFFCBD5E1)

val primaryDark = Color(0xFF60A5FA)
val onPrimaryDark = Color(0xFF0B1E3C)
val primaryContainerDark = Color(0xFF1D4ED8)
val onPrimaryContainerDark = Color(0xFFDCEBFF)

val secondaryDark = Color(0xFF34D399)
val onSecondaryDark = Color(0xFF042F1B)
val secondaryContainerDark = Color(0xFF065F46)
val onSecondaryContainerDark = Color(0xFFBBF7D0)

val tertiaryDark = Color(0xFF8B5CF6)
val onTertiaryDark = Color(0xFF290C5F)
val tertiaryContainerDark = Color(0xFF5B21B6)
val onTertiaryContainerDark = Color(0xFFEDE9FE)

val errorDark = Color(0xFFF87171)
val onErrorDark = Color(0xFF4C1D1D)
val errorContainerDark = Color(0xFF991B1B)
val onErrorContainerDark = Color(0xFFFFE4E0)

val backgroundDark = Color(0xFF111827)
val onBackgroundDark = Color(0xFFE5E7EB)
val surfaceDark = Color(0xFF1F2937)
val onSurfaceDark = Color(0xFFD1D5DB)
val surfaceVariantDark = Color(0xFF374151)
val onSurfaceVariantDark = Color(0xFFC7D2FE)

val outlineDark = Color(0xFF6B7280)
val outlineVariantDark = Color(0xFF4B5563)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE5E7EB)
val inverseOnSurfaceDark = Color(0xFF1F2937)
val inversePrimaryDark = Color(0xFF3B82F6)
val surfaceDimDark = Color(0xFF1E293B)
val surfaceBrightDark = Color(0xFF374151)
val surfaceContainerLowestDark = Color(0xFF0F172A)
val surfaceContainerLowDark = Color(0xFF1E293B)
val surfaceContainerDark = Color(0xFF273443)
val surfaceContainerHighDark = Color(0xFF374151)
val surfaceContainerHighestDark = Color(0xFF4B5563)